--- 
after_script: 
  - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"
before_script: 
  - "curl https://scrutinizer-ci.com/ocular.phar"
language: php
php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
script: 
  - "phpunit --bootstrap test/config.php --coverage-clover coverage.clover test"
